main/urls.py
""" main/urls.py """
from django.urls import path
from .views import wszystkie_filmy, nowy_film, edytuj_film, usun_film,\
                    nowy_review, wszystkie_reviews,search_filmy, film_detail,  new_actor,lista_aktorow, usun_aktora,\
                    actor_detail, actor_edit, new_actor_in_movie, new_actor_in_movie_dt,\
                    adding_actor_from_new_actor_in_movie_dt
from django.conf.urls import url, include
from rest_framework import routers
from .views import UserViewSet, MovieViewSet, ActorViewSet, ReviewViewSet

router = routers.DefaultRouter()
router.register(r'users', UserViewSet)
router.register(r'movies', MovieViewSet)
router.register(r'actors', ActorViewSet)
router.register(r'reviews', ReviewViewSet)


urlpatterns = [
    path('filmy/', wszystkie_filmy, name = 'wszystkie_filmy'),
    path('search/', search_filmy, name = 'search_filmy'),
    path('nowy_film/', nowy_film, name = 'nowy_film'),
    path('edytuj/<int:id>/', edytuj_film, name = 'edytuj_film'),
    path('film_detail/<int:id>/', film_detail, name = 'film_detail'),
    path('new_actor_in_film/<int:id>/', new_actor_in_movie, name = 'new_actor_in_movie'),
    path('new_actor_in_movie_dt/<int:id>/', new_actor_in_movie_dt, name = 'new_actor_in_movie_dt'),
    path('adding_actor_from_new_actor_in_movie_dt/<int:id>/', adding_actor_from_new_actor_in_movie_dt, name = 'adding_actor_from_new_actor_in_movie_dt'),
    path('actor_detail/<int:id>/', actor_detail, name = 'actor_detail'),
    path('usun/<int:id>/', usun_film, name = 'usun_film'),
    path('usun_aktora/<int:id>/', usun_aktora, name = 'usun_aktora'),
    path('edytuj_actor/<int:id>/', actor_edit, name = 'actor_edit'),
    path('filmy/<int:id>/new_review', nowy_review, name = 'nowy_review'),
    path('filmy/<int:id>/reviews', wszystkie_reviews, name = 'wszystkie_reviews'),
    path('nowy_aktor/', new_actor, name = 'new_actor'),
    path('aktorzy/', lista_aktorow, name = 'lista_aktorow'),

    url(r'^', include(router.urls))
]

movierater/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('main/', include('main.urls')),
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
import calendar
from django.db import models


# Create your models here.
class ExtraInfo(models.Model):
    RODZAJE = (
        (0, 'nieznany'),
        (1, 'komedia'),
        (2, 'dramat'),
        (3, 'sci-fi'),
        (4, 'kryminal')
    )

    czas_trwania = models.IntegerField(default=0)
    rodzaj = models.IntegerField(default=0 , choices=RODZAJE)

    def __str__(self):
        return str(self.RODZAJE[self.rodzaj][1]) + ":  " + str(self.czas_trwania)+"min"

class Movie(models.Model):
    name = models.CharField(max_length=128)  # charfield - string
    description = models.TextField(default="")
    year = models.IntegerField(null=True, blank=True)
    released = models.DateField(null=True, blank=True)
    imdb_rating = models.DecimalField(null=True, blank=True, decimal_places=7, max_digits=10)
    photo = models.ImageField(null=True, blank=True, upload_to='filmy')
    info = models.OneToOneField(ExtraInfo, on_delete=models.CASCADE, null=True)


    def __str__(self):
        return self.name_with_year()
    def name_with_year(self):
        return str(self.name) + " ({})".format(str(self.year))


class Review(models.Model):
    RODZAJE = (
        (1, '1'),
        (2, '2'),
        (3, '3'),
        (4, '4'),
        (5, '5')
    )
    text = models.CharField(default="", max_length=500, blank=True, verbose_name='Komentarz')
    stars = models.IntegerField(default=5, verbose_name='Ocena', choices=RODZAJE)
    published_date = models.DateTimeField(blank=True, null=True)
    movie = models.ForeignKey(Movie, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.movie) + " stars: " + str(self.stars) + " " + str(self.text[:5]) + "..."


class Actor(models.Model):
    name = models.CharField(max_length=128,verbose_name='Imię', default="")
    last_name = models.CharField(max_length=128, verbose_name='Nazwisko', default="")
    photo = models.ImageField(null=True, blank=True, upload_to='actors')
    biography = models.CharField(default="", max_length=500, blank=True, verbose_name='Biografia')
    movie = models.ManyToManyField(Movie)

    def __str__(self):
        return str(self.name) + " " + str(self.last_name)

templates/actor_detail.html
<!-- lista_filmow -->
{% extends 'glowny.html' %}
{% block title %} Lista filmów {% endblock %}
<!-- film_form.html -->
{% block body %}
    <div class="jumbotron" >
      <h1 class="display-4">
            {% if user.is_authenticated %}
            <p class="welcome">Witaj, {{ user.username }}</p> <br>  <!-- imie zalogowanego użytkownika -->
                <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
            {% endif %}
      </h1>
    </div>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wszystkie_filmy' %}"><i class="fas fa-film"></i> Filmy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lista_aktorow' %}"><i class="fas fa-users"></i> Aktorzy</a>
      </li>
    </ul>
    <div class = "search_bar">
    <form type="get" action="{% url 'search_filmy'%}" class="form-inline my-10 my-lg-0" >
        <input class="form-control mr-sm-1"  id="search_box" type="search" name="q"  placeholder="Szukaj filmu lub pozostaw pusty by powrócić do listy filmów" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit" > Potwierdź</button>
    </form>
</div>
  </div>
</nav>



 <div class="card">
            <div class="card-body">
                <img src="/media/{{actor.photo}}" alt="plakat">
                <div class="row">
                    <div class="col-sm-10">
                        <h1>{{ actor }}</h1>
                    </div>
                    <div class="col-sm-2">
                        <a href="{% url 'actor_edit' actor.id %}"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'usun_aktora' actor.id %}"><i class="far fa-trash-alt"></i></a>

                    </div>
                </div>
                    <div class="row">
                        <p class="desc">{{ actor.biography }}</p>
                    </div>
            </div>
             <div class="card-body">








<div>
    <h5 style="text-align: center;">Filmografia</h5>
</div>

<a class="nav-link" href="#"><i class="fas fa-plus"></i> Dodaj nowy film</a>
<table class="table table-hover">
    {% for film in actor.movie.all %}
    <tr>
        <th scope="row"><img src="/media/{{film.photo}}" alt="" style="height: 100px, width: 40px; "></th>
        <td colspan="2"></td>
        <td><a href ="{% url 'film_detail' film.id%}" >{{ film }}</a></td>
    </tr>
    {% endfor %}
</table>
            </div>
         </div>


































    {% endblock %}
</div>

templates/aktor_form_db.html
{% extends 'glowny.html' %}
{% block title %} Zapisz{% endblock %}
<!-- film_form.html -->
{% load bootstrap %}
{% block body %}

<div class="film_form">
    <div>

                <td><h5 style="text-align: center;">Aktorzy z bazy danych</h5></td>


</div>
      <div>
        <table>
            <tr>
                <td><a class="nav-link" href="{{request.META.HTTP_REFERER}}"><i class="fas fa-home"></i> Powrót</a></td>
                <td width="35%"></td>
                <td><a class="nav-link" href="{% url 'new_actor_in_movie' film.id %}"><i class="fas fa-plus"></i> Dodaj nowego aktora do bazy danych</a></td>
            </tr>
        </table>
</div>

    <table class="table table-hover">
    {% for item in form %}

    <tr>
        <th scope="row"><img src="/media/{{item.photo}}" alt="" style="height: 100px "></th>
        <td colspan="2"></td>
        <td>{{ item }}<p style="text-align: right;"><button onclick="newwww()" >Dodaj</button></p></td>
    </tr>
    {% endfor %}
</table>
        </div>
    </div>
</div>
{% endblock %}

templates/film_detail.html
<!-- lista_filmow -->
{% extends 'glowny.html' %}
{% block title %} Lista filmów {% endblock %}
<!-- film_form.html -->
{% block body %}
    <div class="jumbotron" >
      <h1 class="display-4">
            {% if user.is_authenticated %}
            <p class="welcome">Witaj, {{ user.username }}</p> <br>  <!-- imie zalogowanego użytkownika -->
                <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
            {% endif %}
      </h1>
    </div>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wszystkie_filmy' %}"><i class="fas fa-film"></i> Filmy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lista_aktorow' %}"><i class="fas fa-users"></i> Aktorzy</a>
      </li><li class="nav-item">
        <a class="nav-link" href="{% url 'nowy_film' %}"><i class="fas fa-plus"></i> Dodaj nowy film</a>
      </li>
    </ul>
    <div class = "search_bar">
    <form type="get" action="{% url 'search_filmy'%}" class="form-inline my-10 my-lg-0" >
        <input class="form-control mr-sm-1"  id="search_box" type="search" name="q"  placeholder="Szukaj filmu lub pozostaw pusty by powrócić do listy filmów" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit" > Potwierdź</button>
    </form>
</div>
  </div>
</nav>


         <div class="card">
            <div class="card-body">
                <img src="/media/{{film.photo}}" alt="plakat">
                <div class="row">
                    {% if film.info is not None %}
                        <p class="desc">{{ film.info }}</p>
                    {% endif %}
                    </div>
                <div class="row">
                    <div class="col-sm-10">
                        <h1>{{ film }}</h1>
                    </div>
                    <div class="col-sm-2">
                        <a href="{% url 'edytuj_film' film.id %}"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'usun_film' film.id %}"><i class="far fa-trash-alt"></i></a>
                        <a href="{% url 'wszystkie_reviews' film.id %}"><i class="far fa-comment"></i></i></a>

                    </div>
                </div>
                    <div class="row">
                        <p class="desc">{{ film.description }}</p>
                    </div>
            </div>
             <div class="card-body">



                 <div>
                        <h5 style="text-align: center;">Obsada</h5>
                    </div>

<td><a class="nav-link" href="{% url 'new_actor_in_movie_dt' film.id %}"><i class="fas fa-plus"></i> dodaj aktora najpierw z bazy, jesli nie ma, dodaj tam nowego aktora</a></td>


<table class="table table-hover">
    {% for actor in film.actor_set.all %}
    <tr>
        <th scope="row"><img src="/media/{{actor.photo}}" alt="" style="height: 100px "></th>
        <td colspan="2"></td>
        <td><a href="{% url 'actor_detail' actor.id %}">{{ actor }}</a></td>
    </tr>
    {% endfor %}
</table>

            </div>
         </div>

    {% endblock %}
</div>

templates/film_form.html
{% extends 'glowny.html' %}
{% block title %} Zapisz film {% endblock %}
<!-- film_form.html -->
{% load bootstrap %}
{% block body %}

<div class="film_form">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Zapisz film</h5>
            <form role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|bootstrap }}
                {{ info }}<br>
                <!-- automatycznie przymie wartość z movierater/urls.py z  auth_views-->
                <button type="submit" class="btn btn-primary"><i class="far fa-save"></i> Zapisz film</button>
                <a href="{% url 'wszystkie_filmy' %}"><button type="button" class="btn btn-secondary">Cofnij</button></a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

templates/glowny.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.3.1/css/all.css"
          integrity="sha384-mzrmE5qonljUremFsqc01SB46JvROS7bZs3IO2EmfFsd15uHvIt+Y8vEf7N7fWAU" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'nowy.css' %}">
    <title>{% block title %}  {% endblock %}</title> <!-- cokolwiek bedzie w title w pozostałych plikach
                                                      zostanie dołączone tutaj -->
</head>
<body>
    {% block body %}  {% endblock %}
</body>
</html>

templates/lista_aktorow.html
<!-- lista_filmow -->
{% extends 'glowny.html' %}
{% block title %} Lista aktorów {% endblock %}
<!-- film_form.html -->
{% block body %}
    <div class="jumbotron" >
      <h1 class="display-4">
            {% if user.is_authenticated %}
            <p class="welcome">Witaj, {{ user.username }}</p> <br>  <!-- imie zalogowanego użytkownika -->
                <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
            {% endif %}
      </h1>
    </div>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wszystkie_filmy' %}"><i class="fas fa-film"></i> Filmy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fas fa-users"></i> Aktorzy</a>
      </li><li class="nav-item">
        <a class="nav-link" href="{% url 'new_actor' %}"><i class="fas fa-plus"></i> Dodaj nowego aktora</a>
      </li>
    </ul>
    <div class = "search_bar">
    <form type="get" action="{% url 'search_filmy'%}" class="form-inline my-10 my-lg-0" >
        <input class="form-control mr-sm-1"  id="search_box" type="search" name="q"  placeholder="Szukaj filmu lub pozostaw pusty by powrócić do listy filmów" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit" > Potwierdź</button>
    </form>
</div>
  </div>
</nav>











        {% for item in form %}
         <div class="card" >
            <div class="card-body">
                <img src="/media/{{item.photo}}" alt="plakat">

                <div class="row">
                    <div class="col-sm-10">
                        <h1><a href="{% url 'actor_detail' item.id %}"> {{ item }}</a></h1>

                    </div>
                    <div class="col-sm-2">
                        <a href="{% url 'actor_edit' item.id %}"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'usun_aktora' item.id %}"><i class="far fa-trash-alt"></i></a>

                    </div>
                </div>


            </div>
         </div>


        {% endfor %}
    {% endblock %}
</div>

templates/lista_filmow.html
<!-- lista_filmow -->
{% extends 'glowny.html' %}
{% block title %} Lista filmów {% endblock %}
<!-- film_form.html -->
{% block body %}
    <div class="jumbotron" >
      <h1 class="display-4">
            {% if user.is_authenticated %}
            <p class="welcome">Witaj, {{ user.username }}</p> <br>  <!-- imie zalogowanego użytkownika -->
                <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
            {% endif %}
      </h1>
    </div>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wszystkie_filmy' %}"><i class="fas fa-film"></i> Filmy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'lista_aktorow' %}"><i class="fas fa-users"></i> Aktorzy</a>
      </li><li class="nav-item">
        <a class="nav-link" href="{% url 'nowy_film' %}"><i class="fas fa-plus"></i> Dodaj nowy film</a>
      </li>
    </ul>
    <div class = "search_bar">
    <form type="get" action="{% url 'search_filmy'%}" class="form-inline my-10 my-lg-0" >
        <input class="form-control mr-sm-1"  id="search_box" type="search" name="q"  placeholder="Szukaj filmu lub pozostaw pusty by powrócić do listy filmów" aria-label="Search">
        <button class="btn btn-outline-primary" type="submit" > Potwierdź</button>
    </form>
</div>
  </div>
</nav>











        {% for film in filmy %}
         <div class="card" >

            <div class="card-body">
                <img src="/media/{{film.photo}}" alt="plakat">
                <div class="row">
                    {% if film.info is not None %}
                        <p class="desc">{{ film.info }}</p>

                    {% endif %}
                    </div>
                <div class="row">
                    <div class="col-sm-10">
                        <h1><a href="{% url 'film_detail' film.id%}">{{ film }}</a></h1>
                    </div>
                    <div class="col-sm-2">
                        <a href="{% url 'edytuj_film' film.id %}"><i class="fas fa-edit"></i></a>
                        <a href="{% url 'usun_film' film.id %}"><i class="far fa-trash-alt"></i></a>
                        <a href="{% url 'wszystkie_reviews' film.id %}"><i class="far fa-comment"></i></i></a>

                    </div>
                </div>
                    <div class="row">
                        <p class="desc">{{ film.description }}</p>
                    </div>

            </div>
         </div>


        {% endfor %}
    {% endblock %}
</div>

templates/lista_review.html
<!-- lista_filmow -->
{% extends 'glowny.html' %}
{% block title %} Lista filmów {% endblock %}
<!-- film_form.html -->
{% block body %}
    <div class="jumbotron" >
      <h1 class="display-4">
            {% if user.is_authenticated %}
            <p class="welcome">Witaj, {{ user.username }}</p> <br>  <!-- imie zalogowanego użytkownika -->
                <a class="btn btn-primary" href="{% url 'logout' %}">Logout</a>
            {% else %}
                <a class="btn btn-primary" href="{% url 'login' %}">Login</a>
            {% endif %}
      </h1>
    </div>

<nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
  <a class="navbar-brand" href="#"></a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#"> <span class="sr-only">(current)</span></a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="{% url 'wszystkie_filmy' %}"><i class="fas fa-film"></i> Filmy</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="#"><i class="fas fa-users"></i> Aktorzy</a>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="{% url 'nowy_review' film.id %}"><i class="fas fa-plus"></i> Dodaj komentarz</a>
      </li>
      </li>
         <li class="nav-item">
        <a class="nav-link" href="{% url 'wszystkie_filmy' %}"><i class="fas fa-home"></i> Cofnij</a>
      </li>
    </ul>
  </div>
</nav>



<a href=""></a>
<a href=""></a>
    {% for item in review %}
         <div class="card" >
            <div class="card-body">
                <div class="row">
                    <div class="col-sm-10">
                        <h5><i class="fas fa-star"> {{ item.stars }}</i></h5>
                        <h5>{{ item.movie }}</h5>
                    </div>

                </div>
                    <div class="row">
                        <p class="desc">{{ item.text }}</p>
                    </div>
            </div>
             {{ item.published_date }}
         </div>
    {% endfor %}

{% endblock %}

templates/potwierdz.html
{% extends 'glowny.html' %}
{% block title %} Potwierdz {% endblock %}
<!-- film_form.html -->
{% block body %}



<div class="card potwierdz" style="width: 600px; margin: auto;">
  <div class="card-body">
     <form method="post">   <!-- bez enctype, bo nie wnosimy tutaj zadnych plikow multimedialnych-->
        {% csrf_token %}
        <div class="alert alert-danger" role="alert">
            <h5>Czy na pewno chcesz usunąć {{ film.name }}</h5>
        </div>
        <button type="submit" class="btn btn-danger">Tak</button>
         <a href="{% url 'wszystkie_filmy' %}"> <button type="button" class="btn btn-success">Nie</button> </a>
    </form>
  </div>
</div>

{% endblock %}

templates/potwierdz_actor.html
{% extends 'glowny.html' %}
{% block title %} Potwierdz {% endblock %}
<!-- film_form.html -->
{% block body %}



<div class="card potwierdz" style="width: 600px; margin: auto;">
  <div class="card-body">
     <form method="post">   <!-- bez enctype, bo nie wnosimy tutaj zadnych plikow multimedialnych-->
        {% csrf_token %}
        <div class="alert alert-danger" role="alert">
            <h5>Czy na pewno chcesz usunąć {{ actor }}</h5>
        </div>
        <button type="submit" class="btn btn-danger">Tak</button>
         <a href="{% url 'lista_aktorow' %}"> <button type="button" class="btn btn-success">Nie</button> </a>
    </form>
  </div>
</div>

{% endblock %}

templates/review_form.html
{% extends 'glowny.html' %}
{% block title %} Zapisz film {% endblock %}
<!-- film_form.html -->
{% load bootstrap %}
{% block body %}



<div class="film_form">
    <div class="card">
        <div class="card-body">
            <h5 class="card-title">Zapisz</h5>
            <form role="form" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ review|bootstrap }}

                <button type="submit" class="btn btn-primary"><i class="far fa-save"></i> Zapisz</button>
                <a href="{{request.META.HTTP_REFERER}}"><button type="button" class="btn btn-secondary">Cofnij</button></a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

<form action=""></form>